# Generated by Django 3.1.6 on 2021-02-15 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('isavailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('seatnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.seat')),
            ],
        ),
    ]
